### ISSUE TITLE
document of  unevenly spaced whittaker

### ISSUE THREAD

**Issue by kongdd** [AnBowell/whittaker-eilers#3]
Dear @AnBowell,

Thanks for your awesome package.
Could you give some reference or equation of unevenly spaced whittaker?

**Comment by AnBowell** [comment]
Thanks for the appreciation! 

You can find the derivation of the unevenly spaced Whittaker in the supporting materials of the original Eilers' paper. 

[https://pubs.acs.org/doi/10.1021/ac034173t](https://pubs.acs.org/doi/10.1021/ac034173t)

You have to scroll down a little, but then you can download the supporting materials PDF.
