### ISSUE TITLE
Maybe add batch processing?

### ISSUE THREAD

**Issue by ikaryss** [AnBowell/whittaker-eilers#6]
Thank you for developing this package! I am currently using it with Python and encountered a limitation when trying to process a batch of signals. The `whittaker_smoother.smooth()` function only accepts 1-D arrays. Maybe add such functionality to process `(batch_size, signal_len)` input?

**Comment by AnBowell** [comment]
I like the idea! 

I think if I were to do this, I'd end up adding some form of multithreading to it too as otherwise it would just be the equivalent of looping over the arrays. I'll have a think about how it could be structured!

**Comment by AnBowell** [comment]
I've released a new version, v0.2.0 which has a basic implementation of this. 

You can smooth many series of data, but it will need to be the same length and have the same x inputs, lambda etc. 

It's implemented in parallel to make it as quick as possible. I think any additions to this for now, such as changing the length of the input or other parameters are outside of the scope of the crate and better implemented by the user.

**Comment by ikaryss** [comment]
That awesome! Thank you so much
